[package]
name = "ode-bevy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode-rs = { version = "0.1.0", path = "../ode-rs" }
bevy = "0.5.0"

[dev-dependencies]
rand = "0.8.4"
